# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: fr-reforme1990
    targetDirectory: .
    compress: false
    format: trie3
    sources:
      - src/hunspell-french-dictionaries-v7.0/fr-reforme1990.dic
      - src/additional_words.txt
    sort: true
    generateNonStrict: true
checksumFile: true
