# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: fr-reforme1990
    targetDirectory: .
    compress: false
    format: trie3
    sources:
      - listFile: source-files.txt
    sort: true
    generateNonStrict: true
