# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: Slovak
    sources:
      - src/Slovak.dic
      - src/additional_words.txt
    format: trie3
    targetDirectory: '.'
    generateNonStrict: true
checksumFile: true
