packages:
  - cspell-dict-file-checker
  - dictionaries/*
  - dictionaries/*/scripts
  - packages/*
  - generator-cspell-dicts
  - scripts

overrides:
  '@cspell/cspell-tools': link:../../code/projects/cspell/packages/cspell-tools
  cspell: link:../../code/projects/cspell/packages/cspell
  cspell-trie: link:../../code/projects/cspell/packages/cspell-trie
  cspell-types: link:../../code/projects/cspell/packages/cspell-types
  hunspell-reader: link:../../code/projects/cspell/packages/hunspell-reader
