# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: sr-cyrl
    targetDirectory: dict
    compress: false
    format: trie3
    sources:
      - listFile: source-files.txt
    sort: true
generateNonStrict: true
