# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: "sr-latn"
    sources:
      - "src/sr-Latn.dic"
    format: "trie3"
    targetDirectory: "./dict"
    generateNonStrict: true
    compress: false
