# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: 'th-th'
    sources:
      - 'src/th_th.txt'
      - filename: src/LibreOffice/th_TH/th_TH.dic
        maxDepth: 3
      - filename: src/syafiqhadzir/th_TH.dic
        maxDepth: 3
    format: 'trie3'
    targetDirectory: './dict'
    generateNonStrict: true
    compress: true
    keepUncompressed: true
checksumFile: true
