#!/usr/bin/env node

// Phase 8 helper: build the branch name / title / body for the PR
// from already-validated data. Kept separate from the create-pull-request
// step so that no user-derived text is ever interpolated directly into a
// `run:`/`script:` block - see docs/issue-to-pr-poc.md.
//
// The body mirrors .github/pull_request_template.md's structure (Dictionary
// / Description / References / Checklist) - GitHub does not auto-apply that
// template when a PR is opened with an explicit body via the API, so it has
// to be reproduced here to keep automated PRs looking like hand-made ones.
//
// Input: $ISSUE_NUMBER, $DICTIONARY, $TARGET_FILE, $ADDED_JSON, $SKIPPED_JSON, $NOTES
// Output (via $GITHUB_OUTPUT): branch, title, body

import { pathToFileURL } from 'node:url';
import { writeOutput } from './lib.mjs';

/**
 * Wrap arbitrary text in a fenced code block sized so the content can't
 * prematurely close it. This is how the issue creator's free-text "Additional
 * Notes" get embedded - as inert text, never markdown/closing-keywords GitHub
 * would act on (e.g. a stray "Fixes #999" in someone's notes must not close
 * an unrelated issue when this PR merges).
 * @param {string} text
 * @returns {string[]}
 */
function codeFence(text) {
    const longestBacktickRun = Math.max(0, ...(text.match(/`+/g) || []).map((run) => run.length));
    const fence = '`'.repeat(Math.max(3, longestBacktickRun + 1));
    return [fence, text, fence];
}

/**
 * @param {{ issueNumber: string, dictionary: string, file: string, added: string[], skipped: string[], notes: string }} input
 */
export function formatPrBody({ issueNumber, dictionary, file, added, skipped, notes }) {
    const lines = [
        '# Add/Fix Dictionary',
        '',
        `Dictionary: \`${dictionary}\``,
        `File: \`${file}\``,
        '',
        '## Description',
        '',
        `Added word(s) submitted in #${issueNumber} via the "Add Words to a Dictionary" issue form:`,
        '',
        ...added.map((word) => `- \`${word}\``),
    ];

    if (skipped.length) {
        lines.push('', 'Already present in the dictionary (not re-added):', ...skipped.map((word) => `- \`${word}\``));
    }

    if (notes) {
        lines.push('', 'Additional notes from the issue creator:', '', ...codeFence(notes));
    }

    lines.push(
        '',
        '## References',
        '',
        `- Fixes #${issueNumber}.`,
        `- Generated by the [issue-to-pr proof-of-concept workflow](../actions/workflows/issue-to-pr.yml).`,
        '',
        '## Checklist',
        '',
        '- [ ] By submitting this pull-request, you agree to follow our [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)',
        '- [x] Verify that the title starts with the correct prefix: `fix:` - for minor changes like adding words or fixing spelling issues.',
        '',
        '_Opened automatically by an automated workflow - please review the sorted/generated output before merging._',
    );

    return lines.join('\n');
}

function main() {
    const issueNumber = process.env.ISSUE_NUMBER || '';
    const dictionary = process.env.DICTIONARY || '';
    const file = process.env.TARGET_FILE || '';
    const added = JSON.parse(process.env.ADDED_JSON || '[]');
    const skipped = JSON.parse(process.env.SKIPPED_JSON || '[]');
    const notes = process.env.NOTES || '';

    writeOutput('branch', `issue-${issueNumber}`);
    writeOutput('title', `fix: add words to ${dictionary} dictionary`);
    writeOutput('body', formatPrBody({ issueNumber, dictionary, file, added, skipped, notes }));
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    main();
}
