# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: "gis-terms"
    sources:
      - filename: "src/gis-terms.txt"
        maxDepth: 1 # This is set to 1 to prevent initial builds from taking too long.
    format: "plaintext"
    targetDirectory: "./dict"
    generateNonStrict: false
    compress: false
