# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: "en-shared"
    sources:
      - "src/shared-additional-words.txt"
    format: "plaintext"
    targetDirectory: "./dict"
    generateNonStrict: false
    compress: false
