# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: 'shared-additional-words'
    sources:
      - filename: src/shared-additional-words.txt
        split: true
    format: plaintext
    targetDirectory: './dict'
    generateNonStrict: false
    compress: false
    excludeWordsFrom:
      - src/exclude-words.txt
  - name: exclude-words
    sources:
      - filename: src/exclude-words.txt
    format: plaintext
    targetDirectory: './dict'
    generateNonStrict: false
