# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: sl_si
    targetDirectory: .
    compress: false
    format: trie3
    sources:
      - src/additional_words.txt
      - src/sl_SI.dic
    sort: true
    generateNonStrict: true
checksumFile: true
