# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: lv
    sources:
      - src/lv.txt
      - src/additional_words.txt
      - src/hunspell/dictionary-lv/index.dic
    format: 'trie3'
    targetDirectory: ./dict
    generateNonStrict: true
    compress: false
checksumFile: true
