# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json
targets:
  - name: typescript
    targetDirectory: ./dict
    compress: false
    format: plaintext
    sources:
      - src/typescript.txt
      - src/ecosystem-terms.txt
    sort: true
keepRawCase: true
