from pathlib import Path
import re
import ast


def findFiles():
    files = Path('temp/python/cpython/Lib').glob('**/*.py')
    # files = Path('temp/python/cpython/Lib').glob('email/p*.py')
    public_files = filter(lambda p: not (
        re.match(r'^_(?!_init__)', p.name) or re.match(
            r'.*\b(test_|_test|test)\b', str(p))
    ), files)
    return public_files


def evalNode(astNode):
    for node in ast.iter_child_nodes(astNode):
        if isinstance(node, ast.FunctionDef) or isinstance(node, ast.ClassDef) or isinstance(node, ast.AsyncFunctionDef):
            name = node.name
            if re.match('^_', name):
                continue
            yield name
            if isinstance(node, ast.ClassDef):
                if not node.col_offset:
                    yield from (name + '.' + method for method in evalNode(node))


def evalFile(file):
    text = open(file, "r").read()
    try:
        p = ast.parse(text)
        return evalNode(p)
    except:
        return ()


print("""
########################
#
# This file is generated by scripts/fetch-python.sh and scripts/extractLib.py
# Do not manually edit this file, run the script instead.
#
# cspell:ignoreRegExp /# temp.*/g
#
########################
""")
for path in findFiles():
    print('# ' + str(path))
    for entry in evalFile(path):
        print(entry)
