# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: 'julia'
    sources:
      - filename: 'src/julia.txt'
        maxDepth: 1 # This is set to 1 to prevent initial builds from taking too long.
      - filename: 'src/julia-keywords.txt'
        maxDepth: 1
    format: 'plaintext'
    targetDirectory: './dict'
    generateNonStrict: false
    compress: false
checksumFile: true
