# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: 'mn-mn'
    sources:
      - filename: 'src/hunspell/index.dic'
        maxDepth: 1 # This is set to 1 to prevent builds from taking too long.
      - src/additional-words.txt
    format: 'trie3'
    targetDirectory: './dict'
    generateNonStrict: true
    compress: false
checksumFile: true
