---
version: "0.2"
files:
  - "**/*.{md,txt}"
language: en,fr
import:
  - "./cspell-ext.json"
ignoreWords:
  - dicollecte
overrides:
  - filename: samples/**
    caseSensitive: true
  - filename: "cspell-ext.json"
    ignoreRegExpList:
      - map-line
      - alphabet-line
patterns:
  - name: map-line
    pattern: >-
      /"map":.*/g
  - name: alphabet-line
    pattern: >-
      /"alphabet":.*/g
words:
  - Bibauw
  - connaît
  - Lefff
  - Leywen
  - Philipp
  - RENOUVO
  - Sagot
