# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: fr-fr
    targetDirectory: .
    compress: false
    format: trie3
    sources:
      - src/additional_words.txt
      - src/hunspell-french-dictionaries-v7.0/fr-classique.dic
    sort: true
    generateNonStrict: true
checksumFile: true
