# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: Turkish
    targetDirectory: .
    format: trie3
    sources:
      - src/hunspell/Turkish.dic
      - src/additional_words.txt
    generateNonStrict: true
checksumFile: true
