# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: "ro-ro"
    sources:
      - src/additional_words.txt
      - src/hunspell/index.dic
      - src/Words-Romanian.txt
    format: "trie3"
    targetDirectory: "./dict"
    generateNonStrict: true
    compress: false
checksumFile: true
