# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: el_GR
    targetDirectory: .
    compress: false
    format: trie3
    sources:
      - src/hunspell/index.dic
      - src/Greek.txt
      - src/additional_words.txt
      - src/Greek.ALLCAPS.txt
    generateNonStrict: true
checksumFile: true
