# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: 'az-az'
    sources:
      - filename: 'src/hunspell/az.dic'
        maxDepth: 3 # This is set to 1 to prevent initial builds from taking too long.
    format: 'trie3'
    targetDirectory: './dict'
    generateNonStrict: true
    compress: true
    keepUncompressed: true
checksumFile: true
