# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: az-az
    sources:
      - src/additional_words.txt
      - filename: 'src/hunspell/az.dic'
        maxDepth: 3
      - src/capitalize-words/capital_i_words.dic
      - src/hugging-face/additional_words.txt
      - src/hugging-face/azerbaijani_spelling_dictionary_2021.txt
    format: trie3
    targetDirectory: './dict'
    generateNonStrict: true
    compress: true
    keepUncompressed: true
checksumFile: true
