# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: 'data-science'
    sources:
      - filename: 'src/data-science-terms.txt'
    format: 'plaintext'
    targetDirectory: './dict'
    compress: false
  - name: 'data-science-models'
    sources:
      - filename: 'src/data-science-models.txt'
        split: true
    format: 'plaintext'
    targetDirectory: './dict'
    compress: false
  - name: 'data-science-tools'
    sources:
      - filename: 'src/data-science-tools.txt'
    format: 'plaintext'
    targetDirectory: './dict'
    compress: false
