# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: "data-science"
    sources:
      - filename: "src/data_science.txt"
        split: true
    format: "plaintext"
    targetDirectory: "./dict"
    generateNonStrict: false
    compress: false
