# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: ca
    sources:
      - src/ca.dic
    format: trie3
    targetDirectory: "."
    generateNonStrict: true
