# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: Spanish
    targetDirectory: .
    compress: false
    format: trie3
    sources:
      - src/additional_words.txt
      - src/hunspell/index.dic
      - src/es_ES/es_ES.dic
    sort: true
    generateNonStrict: true
checksumFile: true
