# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json
targets:
  - name: Portuguese-European
    targetDirectory: dict
    compress: false
    format: trie3
    sources:
      - src/hunspell/Portuguese-European.dic
      - src/additional_words.txt
    sort: true
    generateNonStrict: true
checksumFile: true
