# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: sql
    targetDirectory: .
    compress: true
    format: plaintext
    sources:
      - listFile: source-files.txt
    sort: true
