# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: lorem
    targetDirectory: ./dict
    compress: false
    format: plaintext
    sources:
      - src/dictionary.txt
    sort: true
