# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: 'fullstack'
    sources:
      - filename: src/fullstack.txt
        split: true
    format: plaintext
    targetDirectory: './dict'
    generateNonStrict: false
    compress: false
