# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: nb
    targetDirectory: .
    compress: true
    format: trie3
    sources:
      - src/nb.dic
    sort: true
    generateNonStrict: true
checksumFile: true
