# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: "latex"
    sources:
      - filename: src/latex.txt
        split: legacy
    format: plaintext
    targetDirectory: "./dict"
    generateNonStrict: false
    compress: false
